Document: dvdcopy
Title: Debian dvdcopy Manual
Author: <insert document author here>
Abstract: This manual describes what dvdcopy is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dvdcopy/dvdcopy.sgml.gz

Format: postscript
Files: /usr/share/doc/dvdcopy/dvdcopy.ps.gz

Format: text
Files: /usr/share/doc/dvdcopy/dvdcopy.text.gz

Format: HTML
Index: /usr/share/doc/dvdcopy/html/index.html
Files: /usr/share/doc/dvdcopy/html/*.html
